[versions]

[libraries]
annotations = "org.jetbrains:annotations:26.0.2-1"
java-semver = "io.github.milkdrinkers:javasemver:1.0.2"
json = "org.json:json:20251224"

# Testing
junit-bom = "org.junit:junit-bom:6.0.3"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
junit = ["junit-jupiter", "junit-platform"]

[plugins]
publisher = "com.vanniktech.maven.publish:0.36.0"
shadow = "com.gradleup.shadow:9.3.1"
